# 定义类别数(包括背景)
num_classes: 3
classes_weight: [1., 1., 2.5]  # [1., 1., 2.5]
in_channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
batch_size: 1
num_epochs: 400
unet_base: 32
base_size: [1408, 1536] # [480, 608] [1408, 1536] [1408, 992](分成六块)  [928, 992](分成9快)
unit_size: [700, 600] # 代表一个单元的尺寸，每个单元由四张图片组成，单位是毫米
pixel_shift_ratio: [0, 0]